#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const { detectFamily, generateCode, parseCode } = require('./lib/core')
const runCommon = require('./plugins/common')
const runAwsc = require('./plugins/awsc')
const runObfuscator = require('./plugins/obfuscator')
const runSojson = require('./plugins/sojson')
const runSojsonV7 = require('./plugins/sojsonv7')

const pipelines = {
  common: runCommon,
  awsc: runAwsc,
  obfuscator: runObfuscator,
  sojson: runSojson,
  sojsonv7: runSojsonV7
}

function getArg(flag, fallback) {
  const index = process.argv.indexOf(flag)
  if (index === -1 || index + 1 >= process.argv.length) return fallback
  return process.argv[index + 1]
}

function main() {
  const inputFile = getArg('-i', path.resolve(process.cwd(), 'input.js'))
  const outputFile = getArg('-o', path.resolve(process.cwd(), 'output.js'))
  const code = fs.readFileSync(inputFile, 'utf8')

  const family = detectFamily(code)
  const transform = pipelines[family] || runCommon
  const result = generateCode(transform(parseCode(code)))

  const banner = [
    '// generated by decode_action template-project',
    `// plugin: ${family}`,
    `// input: ${path.basename(inputFile)}`,
    ''
  ].join('\n')

  fs.writeFileSync(outputFile, banner + result, 'utf8')
  console.log(`plugin=${family}`)
  console.log(`output=${outputFile}`)
}

main()
